[Logger]
Level = none
FileLevel = none
Async = false
; ConsoleLevel = info
; SeparateConsole = true   ; uncomment to open a separate console window (Windows only)

[Database]
Host = 127.0.0.1
Type = PostgreSQL Unicode
Port = 5432
Database = dayz_origins
Username = postgres
Password = 0000